package com.google.android.gms.games.internal.player;

import android.text.TextUtils;
/* compiled from: com.google.android.gms:play-services-games-v2@@21.0.0 */
/* loaded from: classes.dex */
public final class zzd {
    public final String zzA;
    public final String zzB;
    public final String zzC;
    public final String zzD;
    public final String zzE;
    public final String zzF;
    public final String zzG;
    public final String zzH;
    public final String zzI;
    public final String zzJ;
    public final String zzK;
    public final String zzL;
    public final String zzM;
    public final String zza;
    public final String zzb;
    public final String zzc;
    public final String zzd;
    public final String zze;
    public final String zzf;
    public final String zzg;
    public final String zzh;
    public final String zzi;
    public final String zzj;
    public final String zzk;
    public final String zzl;
    public final String zzm;
    public final String zzn;
    public final String zzo;
    public final String zzp;
    public final String zzq;
    public final String zzr;
    public final String zzs;
    public final String zzt;
    public final String zzu;
    public final String zzv;
    public final String zzw;
    public final String zzx;
    public final String zzy;
    public final String zzz;

    public zzd(String str) {
        String str2;
        if (TextUtils.isEmpty(null)) {
            this.zza = "external_player_id";
            this.zzb = "game_player_id";
            this.zzc = "profile_name";
            this.zzd = "profile_icon_image_uri";
            this.zze = "profile_icon_image_url";
            this.zzf = "profile_hi_res_image_uri";
            this.zzg = "profile_hi_res_image_url";
            this.zzh = "last_updated";
            this.zzi = "is_in_circles";
            this.zzj = "played_with_timestamp";
            this.zzk = "current_xp_total";
            this.zzl = "current_level";
            this.zzm = "current_level_min_xp";
            this.zzn = "current_level_max_xp";
            this.zzo = "next_level";
            this.zzp = "next_level_max_xp";
            this.zzq = "last_level_up_timestamp";
            this.zzr = "player_title";
            this.zzs = "is_profile_visible";
            this.zzt = "most_recent_external_game_id";
            this.zzu = "most_recent_game_name";
            this.zzv = "most_recent_activity_timestamp";
            this.zzw = "most_recent_game_icon_uri";
            this.zzx = "most_recent_game_hi_res_uri";
            this.zzy = "most_recent_game_featured_uri";
            this.zzz = "has_debug_access";
            this.zzA = "gamer_tag";
            this.zzB = "real_name";
            this.zzC = "banner_image_landscape_uri";
            this.zzD = "banner_image_landscape_url";
            this.zzE = "banner_image_portrait_uri";
            this.zzF = "banner_image_portrait_url";
            this.zzG = "total_unlocked_achievements";
            this.zzH = "play_together_friend_status";
            this.zzI = "play_together_nickname";
            this.zzJ = "play_together_invitation_nickname";
            this.zzK = "nickname_abuse_report_token";
            this.zzL = "friends_list_visibility";
            str2 = "always_auto_sign_in";
        } else {
            this.zza = "nullexternal_player_id";
            this.zzb = "nullgame_player_id";
            this.zzc = "nullprofile_name";
            this.zzd = "nullprofile_icon_image_uri";
            this.zze = "nullprofile_icon_image_url";
            this.zzf = "nullprofile_hi_res_image_uri";
            this.zzg = "nullprofile_hi_res_image_url";
            this.zzh = "nulllast_updated";
            this.zzi = "nullis_in_circles";
            this.zzj = "nullplayed_with_timestamp";
            this.zzk = "nullcurrent_xp_total";
            this.zzl = "nullcurrent_level";
            this.zzm = "nullcurrent_level_min_xp";
            this.zzn = "nullcurrent_level_max_xp";
            this.zzo = "nullnext_level";
            this.zzp = "nullnext_level_max_xp";
            this.zzq = "nulllast_level_up_timestamp";
            this.zzr = "nullplayer_title";
            this.zzs = "nullis_profile_visible";
            this.zzt = "nullmost_recent_external_game_id";
            this.zzu = "nullmost_recent_game_name";
            this.zzv = "nullmost_recent_activity_timestamp";
            this.zzw = "nullmost_recent_game_icon_uri";
            this.zzx = "nullmost_recent_game_hi_res_uri";
            this.zzy = "nullmost_recent_game_featured_uri";
            this.zzz = "nullhas_debug_access";
            this.zzA = "nullgamer_tag";
            this.zzB = "nullreal_name";
            this.zzC = "nullbanner_image_landscape_uri";
            this.zzD = "nullbanner_image_landscape_url";
            this.zzE = "nullbanner_image_portrait_uri";
            this.zzF = "nullbanner_image_portrait_url";
            this.zzG = "nulltotal_unlocked_achievements";
            this.zzH = "nullplay_together_friend_status";
            this.zzI = "nullplay_together_nickname";
            this.zzJ = "nullplay_together_invitation_nickname";
            this.zzK = "nullnickname_abuse_report_token";
            this.zzL = "nullfriends_list_visibility";
            str2 = "nullalways_auto_sign_in";
        }
        this.zzM = str2;
    }
}
